[package]
name = "aws-mfa-session"
version = "0.2.2"
authors = ["Andrii Radyk <ander.ender@gmail.com>"]
description = """
A command line utility to generate temporary AWS credentials with virtual MFA device. Credentials could be exported into new shell or inserted into aws credentials file.
"""
documentation = "https://github.com/AnderEnder/aws-mfa-session"
homepage = "https://github.com/AnderEnder/aws-mfa-session"
repository = "https://github.com/AnderEnder/aws-mfa-session"
readme = "README.md"
keywords = [
    "aws",
    "sts",
    "token",
    "credentials",
]
categories = ["command-line-utilities"]
exclude = [
    ".github/*",
]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3"
dirs = "2"
tokio = { version = "0.2", features = ["full"] }
rusoto_credential = "0.43"
rusoto_signature = "0.43"
regex = "1"

[dependencies.rusoto_core]
version = "0.43"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_iam]
version = "0.43"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_sts]
version = "0.43"
default-features = false
features = [ "rustls" ]

[profile.release]
lto = "fat"
codegen-units = 1
