[package]
name = "aws-mfa-session"
version = "0.2.4"
authors = ["Andrii Radyk <ander.ender@gmail.com>"]
description = """
A command line utility to generate temporary AWS credentials with virtual MFA device. Credentials could be exported into new shell or inserted into aws credentials file.
"""
documentation = "https://github.com/AnderEnder/aws-mfa-session"
homepage = "https://github.com/AnderEnder/aws-mfa-session"
repository = "https://github.com/AnderEnder/aws-mfa-session"
readme = "README.md"
keywords = [
    "aws",
    "sts",
    "token",
    "credentials",
]
categories = ["command-line-utilities"]
exclude = [
    ".github/*",
]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3"
dirs = "3"
tokio = { version = "0.3", features=["macros", "rt-multi-thread"] }
tokio-compat-02 = "0.1"
rusoto_credential = "0.45"
rusoto_signature = "0.45"
regex = "1"

[dependencies.rusoto_core]
version = "0.45"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_iam]
version = "0.45"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_sts]
version = "0.46"
default-features = false
features = [ "rustls" ]

[profile.release]
lto = "thin"
#lto = "fat"
#codegen-units = 1
