[package]
name = "mfa-session"
version = "0.1.0"
authors = ["Andrii Radyk <ander.ender@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
shellexpand = "2"

[dependencies.rusoto_core]
version = "0.42"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_iam]
version = "0.42"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_sts]
version = "0.42"
default-features = false
features = [ "rustls" ]

[profile.release]
lto = "fat"
codegen-units = 1