[package]
name = "mfa-session"
version = "0.2.0"
authors = ["Andrii Radyk <ander.ender@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3"
dirs = "2"
failure = "0.1"
tokio = { version = "0.2", features = ["full"] }
rusoto_credential = "0.43"
rusoto_signature = "0.43"
regex = "1"

[dependencies.rusoto_core]
version = "0.43"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_iam]
version = "0.43"
default-features = false
features = [ "rustls" ]

[dependencies.rusoto_sts]
version = "0.43"
default-features = false
features = [ "rustls" ]

[profile.release]
lto = "fat"
codegen-units = 1
