name: Code check

on: [ pull_request ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/git
            target
          key: clippy-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: clippy check
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: target
          key: fmt-build-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}
          restore-keys: |
            fmt-build-${{ hashFiles('**/Cargo.lock') }}
      - name: fmt check
        run: cargo fmt --all -- --check
