name: Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/git
          target
        key: coverage-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run coverage
      run: |
        docker run \
          --security-opt seccomp=unconfined \
          -v "$(pwd):/volume" \
          xd009642/tarpaulin:latest \
          cargo tarpaulin -f -t 5 --out Xml -v -- --test-threads=1 || true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
